# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'oTenki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Pods for oTenki

end

target 'oTenkiTests' do
  inherit! :search_paths
  pod 'SwiftyJSON'
end 
